spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DB_NAME}
      auto-index-creation: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM}
      sasl.jaas.config: ${KAFKA_JAAS_CONFIG}
      session.timeout.ms: ${KAFKA_SESSION_TIMEOUT}

    producer:
      key-serializer: ${KAFKA_KEY_SERIALIZER}
      value-serializer: ${KAFKA_VALUE_SERIALIZER}
      properties:
        spring.json.add.type.headers: false

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      key-deserializer: ${KAFKA_KEY_DESERIALIZER}
      value-deserializer: ${KAFKA_VALUE_DESERIALIZER}
      properties:
        spring.json.trusted.packages: com.spring.springboot.UrlShortener.model
        spring.json.use.type.headers: false

client:
  id: ${CLIENT_ID}

virustotal:
  api-key: ${VT_API_KEY}
  analysis-url: ${VT_ANALYSIS_URL}

sendgrid:
  api_key: ${SENDGRID_API_KEY}
  verified:
    senders:
      email: ${SENDGRID_EMAIL} #the email which is verified on sendgrid and will be used as from email


